### ISSUE TITLE
Extra print statements cause problems when alerting to SMS

### ISSUE THREAD

**Issue by arpcefxl** [trifthen/NagAconda#9]
When I am sending Nagios alerts to an SMS recipient, the extra print statements that show the range, etc  make it so that I lose much of the content of the alert.  Would it be possible to set a flag for whether or not to send them?  I can fork and upload my own modified copy of Plugin.py for reference if needed (I just commented out many of the print statements).  Thanks!

**Comment by trifthen** [comment]
Just accepted a merge that should fix this.
